name: 'macOS CMake Build'
description: 'Run CMake build and test steps for macOS'

inputs:
  architecture:
    required: true
    description: 'Target architecture (x86_64 or arm64)'
  build-type:
    required: true
    description: 'Build type (editor or game)'
  configuration:
    required: true
    description: 'Build configuration (debug, release, or profile)'

runs:
  using: "composite"
  steps:
    - name: Record build start time
      id: build_start
      shell: bash
      run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build ${{ inputs.architecture }} ${{ inputs.build-type }} in ${{ inputs.configuration }} mode
      uses: lukka/run-cmake@v10
      with:
        configurePreset: macos-clang-${{ inputs.architecture }}${{ inputs.build-type == 'editor' && '-editor' || '' }}
        buildPreset: macos-clang-${{ inputs.architecture }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Test ${{ inputs.architecture }} ${{ inputs.build-type }} in ${{ inputs.configuration }} mode
      continue-on-error: true
      uses: lukka/run-cmake@v10
      with:
        testPreset: test-macos-clang-${{ inputs.architecture }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Record build end time and metrics
      shell: bash
      run: |
        end_time=$(date +%s)
        start_time=${{ steps.build_start.outputs.start_time }}
        duration=$(( (end_time - start_time) / 60 ))
        echo "$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "Build completed for macos-clang-${{ inputs.architecture }}-${{ inputs.build-type }}-${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY
        echo "## Build Metrics" >> $GITHUB_STEP_SUMMARY
        echo "* Architecture: ${{ inputs.architecture }}" >> $GITHUB_STEP_SUMMARY
        echo "* Duration: ${duration} minutes" >> $GITHUB_STEP_SUMMARY
        echo "* Configuration: ${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY