name: 'Linux CMake Build'
description: 'Run CMake build and test steps'

inputs:
  compiler:
    required: true
    description: 'Compiler to use (gcc or clang)'
  build-type:
    required: true
    description: 'Build type (editor or game)'
  configuration:
    required: true
    description: 'Build configuration (debug, release, or profile)'
  configure-preset:
    required: false
    description: 'Optional: explicit CMake configure preset to use (overrides auto-built one)'
  build-preset:
    required: false
    description: 'Optional: explicit CMake build preset to use (overrides auto-built one)'
  test-preset:
    required: false
    description: 'Optional: explicit CMake test preset to use (overrides auto-built one)'

runs:
  using: "composite"
  steps:
    - name: Record build start time
      id: build_start
      shell: bash
      run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Configure (preset override)
      if: ${{ inputs.configure-preset != '' }}
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ inputs.configure-preset }}

    - name: Configure (default)
      if: ${{ inputs.configure-preset == '' }}
      uses: lukka/run-cmake@v10
      with:
        configurePreset: linux-${{ inputs.compiler }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Build (preset override)
      if: ${{ inputs.build-preset != '' }}
      uses: lukka/run-cmake@v10
      with:
        buildPreset: ${{ inputs.build-preset }}

    - name: Build ${{ inputs.build-type }} in ${{ inputs.configuration }} mode
      if: ${{ inputs.build-preset == '' }}
      uses: lukka/run-cmake@v10
      with:
        buildPreset: linux-${{ inputs.compiler }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Test (preset override)
      if: ${{ inputs.test-preset != '' }}
      continue-on-error: true
      uses: lukka/run-cmake@v10
      with:
        testPreset: ${{ inputs.test-preset }}

    - name: Test ${{ inputs.build-type }} in ${{ inputs.configuration }} mode
      if: ${{ inputs.test-preset == '' }}
      continue-on-error: true
      uses: lukka/run-cmake@v10
      with:
        testPreset: test-linux-${{ inputs.compiler }}-${{ inputs.configuration }}${{ inputs.build-type == 'editor' && '-editor' || '' }}

    - name: Record build end time and metrics
      shell: bash
      run: |
        end_time=$(date +%s)
        start_time=${{ steps.build_start.outputs.start_time }}
        duration=$(( (end_time - start_time) / 60 ))
        echo "$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "Build completed for ${{ inputs.compiler }}-${{ inputs.build-type }}-${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY
        echo "## Build Metrics" >> $GITHUB_STEP_SUMMARY
        echo "* Duration: ${duration} minutes" >> $GITHUB_STEP_SUMMARY
        echo "* Configuration: ${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY

    - name: Free disk space (best-effort)
      shell: bash
      continue-on-error: true
      run: |
        set -euo pipefail || true
        echo "=== Freeing disk space (best-effort) ==="

        # apt caches and lists
        sudo apt-get clean -y || true
        sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* || true

        # Docker cleanup (if runner has docker)
        if command -v docker >/dev/null 2>&1; then
          docker system prune -af || true
          docker image prune -af || true
        fi

        # Remove common user caches
        rm -rf "${HOME}/.cache/"* "${HOME}/.npm" "${HOME}/.npm-packages" "${HOME}/.cache/pip" 2>/dev/null || true
        rm -rf "${HOME}/.ccache"/* 2>/dev/null || true
        rm -rf "${HOME}/.local/share/Trash" 2>/dev/null || true

        # Remove temp files
        sudo rm -rf /tmp/* /var/tmp/* 2>/dev/null || true

        # Project-local large cache folders (only if you accept re-download)
        # adjust paths if vcpkg or build dir live elsewhere
        if [ -d "${GITHUB_WORKSPACE}/vcpkg" ]; then
          rm -rf "${GITHUB_WORKSPACE}/vcpkg/buildtrees" "${GITHUB_WORKSPACE}/vcpkg/packages" "${GITHUB_WORKSPACE}/vcpkg/archives" 2>/dev/null || true
        fi
        rm -rf "${GITHUB_WORKSPACE}/build" 2>/dev/null || true
        rm -rf "${GITHUB_WORKSPACE}/.cache" 2>/dev/null || true

        # Node/Python caches inside repo (if present)
        rm -rf "${GITHUB_WORKSPACE}/node_modules" "${GITHUB_WORKSPACE}/.venv" 2>/dev/null || true

        # Run sync to flush FS
        sudo sync || true

        echo "=== Disk usage after cleanup ==="
        df -h || true
        du -sh "${GITHUB_WORKSPACE}" || true