name: 'Windows Build Setup'
description: 'Common build setup steps for Windows builds'

inputs:
  runner_type:
    description: 'Type of runner (GitHub or self-hosted)'
    required: false
    default: 'GitHub'

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/common-config
      id: common-config
      
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: ${{ steps.common-config.outputs.cmake-version }}
        ninjaVersion: ${{ steps.common-config.outputs.ninja-version }}
        
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Clean workspace (self-hosted only)
      if: runner.self-hosted
      shell: pwsh
      run: |
        if (Test-Path "${{ github.workspace }}\vcpkg\downloads\tools") {
          Remove-Item -Recurse -Force "${{ github.workspace }}\vcpkg\downloads\tools"
        }

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'